name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      uses: digreatbrian/buildozer-action@v1
      with:
        workdir: .
